apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
      version: 0.29.1
  install:
    createNamespace: true
    disableWait: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  interval: 5m
  releaseName: vault
  targetNamespace: vault 
  values:
    global:
      enabled: true
      tlsDisable: false
    server:
      # extraEnvironmentVars is a list of extra environment variables to set with the stateful set. These could be
      # used to include variables required for auto-unseal.
      extraEnvironmentVars:
        VAULT_CACERT: /vault/userconfig/tls-ca/ca.crt

      # extraVolumes is a list of extra volumes to mount. These will be exposed
      # to Vault in the path `/vault/userconfig/<name>/`.
      extraVolumes:
        - type: secret
          name: tls-server
        - type: secret
          name: tls-ca

      # This configures the Vault Statefulset to create a PVC for audit logs.
      # See https://www.vaultproject.io/docs/audit/index.html to know more
      auditStorage:
        enabled: true

      standalone:
        enabled: false

      # Run Vault in "HA" mode.
      ha:
        enabled: true
        replicas: 2 
        raft:
          enabled: true
          setNodeId: true

          config: |
            ui = true
            cluster_name = "vault-integrated-storage"
            listener "tcp" {
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              tls_cert_file = "/vault/userconfig/tls-server/vault.crt"
              tls_key_file = "/vault/userconfig/tls-server/tls.key"
            }

            storage "raft" {
              path = "/vault/data"
              retry_join {
                leader_api_addr = "https://vault-0.vault-internal:8200"
                leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
                leader_client_cert_file = "/vault/userconfig/tls-server/vault.crt"
                leader_client_key_file = "/vault/userconfig/tls-server/vault.key"
              }
              retry_join {
                leader_api_addr = "https://vault-1.vault-internal:8200"
                leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
                leader_client_cert_file = "/vault/userconfig/tls-server/vault.crt"
                leader_client_key_file = "/vault/userconfig/tls-server/vault.key"
              }
              #   retry_join {
              # leader_api_addr = "https://vault-2.vault-internal:8200"
              # leader_ca_cert_file = "/vault/userconfig/tls-ca/ca.crt"
              #  leader_client_cert_file = "/vault/userconfig/tls-server/vault.crt"
              #  leader_client_key_file = "/vault/userconfig/tls-server/vault.key"
              # }
            } 

    # Vault UI
    ui:
      enabled: true
      serviceType: "ClusterIP"
      serviceNodePort: null
      externalPort: 8200
