apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
      version: 0.29.1
  install:
    createNamespace: true
    disableWait: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  interval: 5m
  releaseName: vault
  targetNamespace: vault 
  values:
    server:
      affinity: ""
      ha:
        enabled: true
        raft: 
          enabled: true
          setNodeId: true
          config: |
            cluster_name = "vault-integrated-storage"
            storage "raft" {
              path    = "/vault/data/"
            }
            listener "tcp" {
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              tls_disable = "true"
            }
            service_registration "kubernetes" {}
